CRUISE_MODE_MAX_SPEED: 90  # Maximum speed for cruise control mode in mph
CRUISE_MODE_MIN_SPEED: 20  # Minimum speed for cruise control mode in mph
HISTORIC_CC_FILE_NAME: "cruise_control_speeds.json"  # Filename for storing historical cruise control speeds
INIT_SPEED: 40  # Initial speed of the vehicle in mph
LOG_FILE_NAME: "log.json"  # Filename for logging data
MANUAL_MODE_MAX_SPEED: 100  # Maximum speed of the vehicle in mph
MANUAL_MODE_MIN_SPEED: 10  # Minimum speed for manual mode in mph
SIM_RATE: 10  # Simulation rate in Hz
SPEED_AVG_WIN_SIZE: 20  # Time window in seconds for calculating the average speed
